#!/usr/bin/env python3
"""
Phase 6 simulation CLI — runs operational impact simulation.

Usage:
    python scripts/run_simulation.py

Expected inputs (generated by previous phases):
    orders.csv, order_lines.csv, zones.csv, locations.csv,
    inventory.csv, optimization_assignments.csv

Outputs (written to ``data/processed/``):
    - simulation_summary.csv         — top-level metrics
    - simulation_travel_aggregate.csv — travel distance/time metrics
    - simulation_zone_impact.csv     — per-zone pick counts (pre / post)
    - simulation_throughput_scenarios.csv — throughput comparison
    - simulation_order_detail.csv    — top-N order-level detail
"""

from __future__ import annotations

import sys
from pathlib import Path

# Ensure the package is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from slotting_optimization_engine.simulation.config import SimulationConfig
from slotting_optimization_engine.simulation.report import (
    build_simulation_report,
    save_simulation_outputs,
)
from slotting_optimization_engine.simulation.throughput import estimate_throughput
from slotting_optimization_engine.simulation.travel import (
    build_sku_current_zone,
    build_sku_optimized_zone,
    load_simulation_inputs,
    simulate_travel,
)
from slotting_optimization_engine.simulation.workload import simulate_workload


def main() -> int:
    config = SimulationConfig()

    print("=" * 60)
    print("PHASE 6 — Operational Impact Simulation")
    print("=" * 60)

    # Step 1 — Load inputs
    print("\n[1/6] Loading simulation inputs ...")
    inputs = load_simulation_inputs()
    print(f"      orders: {len(inputs['orders'])}")
    print(f"      order_lines: {len(inputs['order_lines'])}")
    print(f"      zones: {len(inputs['zones'])}")
    print(f"      locations: {len(inputs['locations'])}")
    print(f"      inventory: {len(inputs['inventory'])}")
    print(f"      optimization_assignments: {len(inputs['optimization_assignments'])}")

    # Step 2 — Build SKU→zone mappings
    print("\n[2/6] Building SKU → zone mappings ...")
    sku_current = build_sku_current_zone(inputs["inventory"], inputs["locations"])
    sku_optimized = build_sku_optimized_zone(inputs["optimization_assignments"])
    print(f"      SKUs with current zone: {len(sku_current)}")
    print(f"      SKUs with optimised zone: {len(sku_optimized)}")

    # Step 3 — Travel simulation
    print("\n[3/6] Simulating travel distance / time ...")
    travel_result = simulate_travel(
        inputs["order_lines"],
        inputs["zones"],
        sku_current,
        sku_optimized,
        config,
    )
    travel_agg = travel_result["aggregate"]
    print(f"      Current total distance: {travel_agg['total_current_distance_m']:,.0f} m")
    print(f"      Optimised total distance: {travel_agg['total_optimized_distance_m']:,.0f} m")
    print(f"      Distance saved: {travel_agg['total_distance_saved_m']:,.0f} m")
    print(f"      Time saved: {travel_agg['total_time_saved_s']:,.0f} s")
    print(f"      Avg improvement: {travel_agg['avg_improvement_pct']} %")

    # Step 4 — Workload simulation
    print("\n[4/6] Simulating zone workload balance ...")
    workload_result = simulate_workload(
        inputs["order_lines"],
        inputs["zones"],
        sku_current,
        sku_optimized,
        config,
    )
    wl_agg = workload_result["aggregate"]
    print(f"      Gini before: {wl_agg['gini_coefficient_before']}")
    print(f"      Gini after: {wl_agg['gini_coefficient_after']}")
    print(f"      Balance improved: {wl_agg['balance_improved']}")

    # Step 5 — Throughput estimation
    print("\n[5/6] Estimating throughput impact ...")
    throughput_result = estimate_throughput(travel_result, config)
    th_agg = throughput_result["aggregate"]
    print(f"      Orders/shift current: {th_agg['orders_per_shift_current']:,.0f}")
    print(f"      Orders/shift optimised: {th_agg['orders_per_shift_optimized']:,.0f}")
    rec = th_agg['recommended_scenario']
    print(f"      Throughput gain: {th_agg['throughput_gain_pct']} % ({rec})")

    # Step 6 — Build and save report
    print("\n[6/6] Building and saving simulation report ...")
    reports = build_simulation_report(travel_result, workload_result, throughput_result)
    paths = save_simulation_outputs(reports)

    print("\n" + "=" * 60)
    print("SIMULATION COMPLETE")
    print("=" * 60)
    for key, path in paths.items():
        print(f"  {key}: {path}")
    print(f"\nCaveat: {config.simulation_caveat}")
    print("All weights and thresholds are inferred / pending confirmation.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
