#!/usr/bin/env python3
"""
Phase 6 simulation CLI — runs operational impact simulation.

Usage:
    python scripts/run_simulation.py                          # All 3 scenarios
    python scripts/run_simulation.py --scenario-a             # Travel only (Escenario A)
    python scripts/run_simulation.py --scenarios travel       # Travel only
    python scripts/run_simulation.py --scenarios travel,throughput
    python scripts/run_simulation.py --list-scenarios         # List available

Expected inputs (generated by previous phases):
    orders.csv, order_lines.csv, zones.csv, locations.csv,
    inventory.csv, optimization_assignments.csv

Outputs (written to ``data/processed/``):
    - simulation_summary.csv         — top-level metrics
    - simulation_travel_aggregate.csv — travel distance/time metrics
    - simulation_zone_impact.csv     — per-zone pick counts (pre / post)
    - simulation_throughput_scenarios.csv — throughput comparison
    - simulation_order_detail.csv    — top-N order-level detail
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Ensure the package is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from slotting_optimization_engine.simulation.config import SimulationConfig
from slotting_optimization_engine.simulation.pipeline import (
    SimulationContext,
    SimulationPipeline,
)
from slotting_optimization_engine.simulation.registry import (
    ALL_SCENARIOS,
    BUILTIN_SCENARIOS,
)
from slotting_optimization_engine.simulation.report import (
    build_report_from_pipeline,
    save_simulation_outputs,
)
from slotting_optimization_engine.simulation.travel import (
    build_sku_current_zone,
    build_sku_optimized_zone,
    load_simulation_inputs,
)
from slotting_optimization_engine.simulation.workload import (  # noqa: F401
    gini_coefficient,
    simulate_workload,
)


def _build_context(config: SimulationConfig) -> SimulationContext:
    """Load inputs and build SKU→zone mappings into a shared context."""
    inputs = load_simulation_inputs()

    sku_current = build_sku_current_zone(
        inputs["inventory"], inputs["locations"]
    )
    sku_optimized = build_sku_optimized_zone(
        inputs["optimization_assignments"]
    )

    return SimulationContext(
        orders=inputs["orders"],
        order_lines=inputs["order_lines"],
        zones=inputs["zones"],
        locations=inputs["locations"],
        inventory=inputs["inventory"],
        optimization_assignments=inputs["optimization_assignments"],
        sku_current_zone=sku_current,
        sku_optimized_zone=sku_optimized,
        config=config,
    )


def _print_summary(context: SimulationContext, results: dict) -> None:
    """Print human-readable summary of key metrics."""
    travel = results.get("travel", {}).get("aggregate", {})
    workload = results.get("workload", {}).get("aggregate", {})
    throughput = results.get("throughput", {}).get("aggregate", {})

    if travel:
        print(
            f"\n[Travel] Current: {travel.get('total_current_distance_m', 'N/A'):,.0f} m  "
            f"Optimised: {travel.get('total_optimized_distance_m', 'N/A'):,.0f} m  "
            f"Saved: {travel.get('total_distance_saved_m', 'N/A'):,.0f} m  "
            f"Avg improvement: {travel.get('avg_improvement_pct', 'N/A')} %"
        )
    if workload:
        print(
            f"[Workload] Gini before: {workload.get('gini_coefficient_before', 'N/A')}  "
            f"after: {workload.get('gini_coefficient_after', 'N/A')}  "
            f"Improved: {workload.get('balance_improved', 'N/A')}"
        )
    if throughput:
        curr = throughput.get('orders_per_shift_current', 'N/A')
        opt = throughput.get('orders_per_shift_optimized', 'N/A')
        gain = throughput.get('throughput_gain_pct', 'N/A')
        scen = throughput.get('recommended_scenario', 'N/A')
        print(
            f"[Throughput] Orders/shift: {curr:,} → {opt:,}  "
            f"Gain: {gain} % ({scen})"
        )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Phase 6 — Operational Impact Simulation"
    )
    parser.add_argument(
        "--scenarios",
        type=str,
        default="travel,workload,throughput",
        help=(
            "Comma-separated scenario names to run. "
            "Default: all (travel,workload,throughput). "
            "Use --list-scenarios to see available options."
        ),
    )
    parser.add_argument(
        "--scenario-a",
        action="store_true",
        help="Shortcut for --scenarios travel (distance-only scenario).",
    )
    parser.add_argument(
        "--list-scenarios",
        action="store_true",
        help="List available scenarios and exit.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Load inputs and print SKU counts without running simulation.",
    )
    args = parser.parse_args()

    if args.list_scenarios:
        print("Available simulation scenarios (Scenario C framework):")
        print()
        for name, desc in sorted(ALL_SCENARIOS.items()):
            print(f"  {name:<15s} {desc}")
        print()
        print("Usage: python scripts/run_simulation.py --scenarios travel,workload")
        print("       python scripts/run_simulation.py --scenarios travel")
        print("       python scripts/run_simulation.py --scenario-a")
        return 0

    # --scenario-a is a convenience alias for --scenarios travel
    if args.scenario_a:
        args.scenarios = "travel"

    config = SimulationConfig()

    print("=" * 60)
    print("PHASE 6 — Operational Impact Simulation")
    print(f"Scenarios: {args.scenarios}")
    print("=" * 60)

    # Step 1 — Load inputs
    print("\n[1/5] Loading simulation inputs and building context ...")
    context = _build_context(config)
    def _fmt_len(df, label):
        count = len(df) if df is not None else 0
        print(f"      {label}: {count}")

    _fmt_len(context.orders, "orders")
    _fmt_len(context.order_lines, "order_lines")
    _fmt_len(context.zones, "zones")
    _fmt_len(context.locations, "locations")
    _fmt_len(context.inventory, "inventory")
    _fmt_len(context.optimization_assignments, "optimization_assignments")
    _fmt_len(context.sku_current_zone, "SKUs with current zone")
    _fmt_len(context.sku_optimized_zone, "SKUs with optimised zone")

    if args.dry_run:
        print("\nDry run complete — no simulation executed.")
        return 0

    # Step 2 — Resolve scenarios and run pipeline
    scenario_list = [s.strip() for s in args.scenarios.split(",") if s.strip()]
    print(f"\n[2/5] Running pipeline with scenarios: {scenario_list} ...")
    pipeline = SimulationPipeline(scenario_list, registry=BUILTIN_SCENARIOS)
    results = pipeline.run(context)

    # Step 3 — Print summary
    print("\n[3/5] Results summary:")
    _print_summary(context, results)

    # Step 4 — Build and save report
    print("\n[4/5] Building simulation report ...")
    reports = build_report_from_pipeline(results, context)

    print("[5/5] Saving CSV outputs ...")
    paths = save_simulation_outputs(reports)

    print("\n" + "=" * 60)
    print("SIMULATION COMPLETE")
    print("=" * 60)
    for key, path in paths.items():
        print(f"  {key}: {path}")
    print(f"\nCaveat: {config.simulation_caveat}")
    print("All weights and thresholds are inferred / pending confirmation.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
